[build]
  publish = "dist"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://gtback-production.up.railway.app"

[context.deploy-preview.environment]
  VITE_API_URL = "https://gtback-production.up.railway.app"

[context.branch-deploy.environment]
  VITE_API_URL = "https://gtback-production.up.railway.app"

